# Generated by Django 4.2.30 on 2026-08-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('agendamentos', '0002_alter_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('duracao_aula', models.PositiveIntegerField(choices=[(30, '30 minutos'), (60, '60 minutos'), (90, '90 minutos'), (120, '120 minutos')], default=60)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AlterModelOptions(
            name='disponibilidade',
            options={'ordering': ['data', 'hora_inicio']},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='disponibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agendamentos.disponibilidade'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidade',
            constraint=models.UniqueConstraint(fields=('professor', 'data', 'hora_inicio', 'hora_fim'), name='disponibilidade_horario_unico'),
        ),
        migrations.AddField(
            model_name='regradisponibilidade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_disponibilidade', to='professores.professor'),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_gerados', to='agendamentos.regradisponibilidade'),
        ),
        migrations.AddConstraint(
            model_name='regradisponibilidade',
            constraint=models.UniqueConstraint(fields=('professor', 'dia_semana', 'hora_inicio', 'hora_fim'), name='regra_disponibilidade_unica'),
        ),
    ]
