# Generated by Django 4.2.30 on 2026-09-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_trilha_tecnica_progressoaluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilha',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
