# Generated by Django 4.2.30 on 2026-09-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0005_alter_trilha_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilhaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_aprendizado', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_alunos', to='professores.professor')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='agendamentos.trilha')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trilhaaluno',
            constraint=models.UniqueConstraint(fields=('professor', 'aluno'), name='trilha_aluno_professor_unica'),
        ),
    ]
