# Generated by Django 4.2.30 on 2026-09-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_trilhaaluno_trilhaaluno_trilha_aluno_professor_unica'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='agendamentos.trilha')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tecnica',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicas', to='agendamentos.categoriatecnica'),
        ),
    ]
