# Generated by Django 4.2.30 on 2026-09-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
        ('agendamentos', '0007_categoriatecnica_tecnica_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='professores.professor'),
        ),
        migrations.AlterField(
            model_name='trilha',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='trilha',
            constraint=models.UniqueConstraint(fields=('professor', 'nome'), name='trilha_professor_nome_unico'),
        ),
    ]
