# Generated by Django 4.2.30 on 2026-09-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_trilha_professor_alter_trilha_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressoaluno',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='progressoaluno',
            name='tecnica',
        ),
        migrations.RemoveField(
            model_name='tecnica',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='tecnica',
            name='trilha',
        ),
        migrations.RemoveField(
            model_name='trilha',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='trilhaaluno',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='trilhaaluno',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='trilhaaluno',
            name='trilha',
        ),
        migrations.DeleteModel(
            name='CategoriaTecnica',
        ),
        migrations.DeleteModel(
            name='ProgressoAluno',
        ),
        migrations.DeleteModel(
            name='Tecnica',
        ),
        migrations.DeleteModel(
            name='Trilha',
        ),
        migrations.DeleteModel(
            name='TrilhaAluno',
        ),
    ]
