# Generated by Django 4.2.30 on 2026-09-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agendamentos_categoriatecnica',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='professores.professor')),
            ],
            options={
                'db_table': 'agendamentos_trilha',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_aprendizado', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas_alunos', to='professores.professor')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='trilhas.trilha')),
            ],
            options={
                'db_table': 'agendamentos_trilhaaluno',
            },
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicas', to='trilhas.categoriatecnica')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='trilhas.trilha')),
            ],
            options={
                'db_table': 'agendamentos_tecnica',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendido', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_tecnicas', to=settings.AUTH_USER_MODEL)),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='trilhas.tecnica')),
            ],
            options={
                'db_table': 'agendamentos_progressoaluno',
            },
        ),
        migrations.AddField(
            model_name='categoriatecnica',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='trilhas.trilha'),
        ),
        migrations.AddConstraint(
            model_name='trilhaaluno',
            constraint=models.UniqueConstraint(fields=('professor', 'aluno'), name='trilha_aluno_professor_unica'),
        ),
        migrations.AddConstraint(
            model_name='trilha',
            constraint=models.UniqueConstraint(fields=('professor', 'nome'), name='trilha_professor_nome_unico'),
        ),
        migrations.AddConstraint(
            model_name='progressoaluno',
            constraint=models.UniqueConstraint(fields=('aluno', 'tecnica'), name='progresso_aluno_tecnica_unico'),
        ),
    ]
