# Generated by Django 4.2.30 on 2026-05-28 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(max_length=50)),
                ('biografia', models.TextField()),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cidade', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='professores/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
